azure:
  free_disk_space: true
  store_build_artifacts: true
build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
  win_64: linux_64
  osx_64: osx_64
  osx_arm64: osx_64
test: native_and_emulated
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
