build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
  linux_s390x: linux_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
azure:
  store_build_artifacts: True
